name: Test Coverage ðŸ§ªðŸ“Š

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code ðŸ“¥
        uses: actions/checkout@v2

      - name: Read .nvmrc ðŸ“„
        id: nvmrc
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - name: Set up Node.js ðŸŒ
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies ðŸ“¦
        run: yarn install

      - name: Run tests and generate coverage ðŸƒâ€â™‚ï¸ðŸ’»
        run: yarn test --coverage

      - name: Write coverage to a separate file ðŸ“
        run: |
          COVERAGE=$(grep -oE 'All files\s+\|\s+\K[0-9]+(\.[0-9]+)?(?=%)' coverage/lcov.info | head -n 1)
          TOTAL_TESTS=$(grep -oE 'Tests\s+\|\s+\K[0-9]+' coverage/lcov.info | head -n 1)
          PASSED_TESTS=$(grep -oE 'Passes\s+\|\s+\K[0-9]+' coverage/lcov.info | head -n 1)
          DATE=$(date +"%Y-%m-%d %H:%M:%S")

          echo "## Test Coverage Report ðŸ“" > COVERAGE.md
          echo "" >> COVERAGE.md
          echo "Date: $DATE" >> COVERAGE.md
          echo "" >> COVERAGE.md
          echo "Total Tests: $TOTAL_TESTS" >> COVERAGE.md
          echo "Passed Tests: $PASSED_TESTS" >> COVERAGE.md
          echo "Overall Coverage: $COVERAGE%" >> COVERAGE.md
          echo "" >> COVERAGE.md
          echo "### File Coverage Details:" >> COVERAGE.md
          echo "" >> COVERAGE.md
          
          grep -E '^\s+\S+\s+\|\s+\d+(\.\d+)?%' coverage/lcov.info >> COVERAGE.md
          echo "" >> COVERAGE.md  # Add a blank line at the end

          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add COVERAGE.md
          git commit -m "docs: update coverage report: $COVERAGE%"
          git push

      - name: Clean up ðŸ§¹
        run: |
          # Clean up the coverage folder if needed
          rm -rf coverage
